spring:
  
  servlet:
    multipart:
      enabled: true
  
  application:
    name: crianca-engenharia-api
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: update
    show-sql: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost:5432/crianca-engenharia-2019
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  mail:
    test-connection: true
    host: smtp.gmail.com
    port: 587
    username: engenhariacrianca@gmail.com
    password: Criancaengenharia
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
        ssl:
          enable: true
        
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 8080
